import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'George Reade: Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><link rel="icon" href="./images/ouroboros.jpg"/>    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com"/>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;200;400;700&display=swap" rel="stylesheet"/></head>
      <body>{children}</body>
    </html>
  )
}
